# Generated by Django 4.1.1 on 2022-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('currentlocation', models.CharField(max_length=30)),
                ('starttime', models.DateTimeField(null=True)),
                ('endtime', models.DateTimeField(null=True)),
                ('served', models.BooleanField(default=False, verbose_name='Served')),
                ('created', models.DateTimeField(null=True)),
            ],
        ),
    ]
