# Generated by Django 4.1.1 on 2022-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_client_created_alter_driver_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='idcard',
            field=models.FileField(upload_to='driverdocs/IdFolder'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licensecard',
            field=models.FileField(upload_to='driverdocs/LicenseFolder'),
        ),
    ]
