# Generated by Django 4.1.1 on 2022-11-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_driver_idcard_alter_driver_licensecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
